webinar api and transcoding
netology-group/dispatcher pull request #4
Opened 2021-02-17 08:57 UTC by khodzha

2021-02-17 11:48 UTC, manifest commented on src/app/api/v1/webinar/mod.rs
> +            Bound::Included(t - chrono::Duration::minutes(10)),
What are these `chrono::Duration::minutes(10)`?

2021-02-17 11:48 UTC, manifest commented on src/app/mod.rs
> +    app.at("/api/v1/webinars/:id").patch(update_webinar);
Why do we need `PATCH`?

2021-02-17 11:48 UTC, manifest commented on src/app/tide_state/tq_client.rs
> +        /*
?

2021-02-17 13:18 UTC, khodzha commented on src/app/mod.rs
> +    app.at("/api/v1/webinars/:id").patch(update_webinar);
rails has both patch and put method as convention for updating entities, its convenient to provide both patch and put here too

2021-02-17 13:20 UTC, khodzha commented on src/app/api/v1/webinar/mod.rs
> +            Bound::Included(t - chrono::Duration::minutes(10)),
this is a window when viewers can enter a conference room to do presignaling in new signaling flow

2021-02-17 13:21 UTC, khodzha commented on src/app/api/v1/webinar/mod.rs
> +            Bound::Included(t - chrono::Duration::minutes(10)),
moved it to a constant

2021-02-18 12:02 UTC, feymartynov requested changes

2021-02-19 09:37 UTC, manifest commented on src/app/api/v1/webinar/mod.rs
> +            Bound::Included(t - chrono::Duration::minutes(10)),
Lets move it to the config.

2021-02-19 09:37 UTC, manifest commented on src/app/mod.rs
> +    app.at("/api/v1/webinars/:id").patch(update_webinar);
Don't see the point.

2021-02-19 10:12 UTC, manifest commented on src/app/tide_state/mod.rs
> +    fn validate_token(&self, token: Option<&str>) -> Result<(), Error> {
Where are we going to use it?

2021-03-09 12:28 UTC, khodzha commented on src/app/api/v1/webinar/mod.rs
> +struct RealTimeObject {
no, this is `real_time` field in the "webinar object" payload

2021-03-09 12:29 UTC, khodzha commented on src/app/api/v1/webinar/mod.rs
> +            Bound::Included(t - chrono::Duration::minutes(10)),
this is outdated since new signaling was never deployed

2021-03-09 12:29 UTC, khodzha commented on src/app/mod.rs
> +    app.at("/api/v1/webinars/:id").patch(update_webinar);
fixed

2021-03-09 12:29 UTC, khodzha commented on docs/src/webinars/api.md
> +Все роуты ожидают json на входе
fixed

2021-03-09 12:29 UTC, khodzha commented on src/app/tide_state/conference_client.rs
> +            unreachable!()
addressed

2021-03-10 15:09 UTC, manifest approved these changes

2021-03-16 11:11 UTC, feymartynov requested changes

2021-03-16 11:11 UTC, feymartynov commented on docs/src/webinars/api.md
> +preserve_history       | bool        | +        | History preservation enabled or not.
I think this parameter is redundand since it would always be `true`. If someone sets it to `false` that would break the recording.

2021-03-16 11:11 UTC, feymartynov commented on src/app/api/v1/webinar/mod.rs
> +    stream_id: Uuid,
This has been done wrong in the initial tenant integration and now it's copypasted here.
`stream_id` is actually `rtc_id` and should be in `RealTimeObject` because RTC id never gets changed.

2021-03-18 13:51 UTC, khodzha commented on docs/src/webinars/api.md
> +preserve_history       | bool        | +        | History preservation enabled or not.
this is fixed in convert_api branch

2021-03-18 15:03 UTC, khodzha commented on src/app/api/v1/webinar/mod.rs
> +    stream_id: Uuid,
this is fixed in classrooms branch

2021-03-18 15:03 UTC, merged